spring.application.name=messenger

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:25432/mydatabase}
spring.datasource.username=${DB_USERNAME:myuser}
spring.datasource.password=${DB_PASSWORD:secret}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:26379}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29094,localhost:29096}

jwt.secret=${JWT_SECRET:qwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwerty}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

logging.level.org.springframework.security=DEBUG
