apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
        - name: kafka3
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "3"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka1-service:9093,2@kafka2-service:9095,3@kafka3-service:9097"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9096,CONTROLLER://0.0.0.0:9097"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka3-service:9096"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: CLUSTER_ID
              value: "Mk3OEYBSD34fcwNTJENDM2Qk"
          ports:
            - containerPort: 9096
            - containerPort: 9097
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3-service
spec:
  selector:
    app: kafka3
  ports:
    - port: 9096
      name: "kafka3-port1"
      targetPort: 9096
    - port: 9097
      name: "kafka3-port2"
      targetPort: 9097
