apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
        - name: kafka2
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "2"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka1-service:9093,2@kafka2-service:9095,3@kafka3-service:9097"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka2-service:9094"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: CLUSTER_ID
              value: "Mk3OEYBSD34fcwNTJENDM2Qk"
          ports:
            - containerPort: 9094
            - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
spec:
  selector:
    app: kafka2
  ports:
    - port: 9094
      name: "kafka2-port1"
      targetPort: 9094
    - port: 9095
      name: "kafka2-port2"
      targetPort: 9095
